### ISSUE TITLE
2020-04-02, 5th review

### ISSUE THREAD

**Issue by jongfeel** [hhlvv/omo#23]
### 작업 결과 리뷰 (등록된 issue에서, 체크박스 체크 기준)

- album style image layout
- 반응형 기능: 슬라이더
- 문자, 전화 기능
- 지도 기능
- 소셜 공유 기능

### 실제 확인 결과

- master branch 기준 실행
```
npm run serve
```
- 적용 된게 앨범 스타일 이미지 레이아웃 정도인 것 같네요.

**Comment by hhlvv** [comment]
dev 브런치를 master에 추가 하였습니다. 이미지는 적용하지 않은 상태입니다
현재 소셜 공유기능에 fontawesome이 작동하지 않아 이미지가 안보이는 문제 해결중이에요

**Comment by jongfeel** [comment]
### 앨범 스타일 이미지 레이아웃

- 한번에 1개 + 1/4 정도의 이미지가 나올거면 슬라이더 기능이 필요할까...?를 고민해 보면 좋을 거 같아요 => 2x5 정도 이미지 배치하는 건 어떨까요?

**Comment by jongfeel** [comment]
### AWS 준비
- node 서버 올리기
