### ISSUE TITLE
6th schedule plan

### ISSUE THREAD

**Issue by jongfeel** [hhlvv/omo#25]
### 주중

- 1주, 3회, 7시간 

### 주말

- 1주, 2회, 3시간

나중에 잊어버리지 않기 위해
가능하다면 계획한대로 실천했는지 체크 하시고 기록해 주시면 좋겠습니다.
(알람 계속 와도 상관 없으니까 해주세요)

**Comment by hhlvv** [comment]
1주 스케줄( 04.03 ~ 04.09 )

- [x] 금요일 2시간
- [x] 토요일 1시간
- [ ] 일요일 2시간
- [x] 월요일 3시간
- [ ] 수요일 2시간

**Comment by hhlvv** [comment]
금요일 2시간[○] _ 화면 및 자잘한 기능 수정
토요일 1시간 예정_ AWS 초기 설정

**Comment by hhlvv** [comment]
토요일 1시간 _ AWS EC2 생성하고 putty로 접속하는것 (키 생성까진 했는데 접속 유저랑 이름에서 찾지 못함...)

**Comment by hhlvv** [comment]
월요일 2시간 반_ 3시간은..주중에 마음을 먹어도 집중이 힘듦...😢
- 키 등록이 제대로 되지 않았어서 접속에 문제가 있었음. 서버에 접속이 잘 됨

**Comment by jongfeel** [comment]
이후 계획은 #27 참고
