### ISSUE TITLE
Component Layout

### ISSUE THREAD

**Issue by hhlvv** [hhlvv/omo#6]
https://awesome-vue.js.org/components-and-libraries/ui-layout.html
참고하여 수정
레이아웃을 받아서 어떻게 적용해야 할지..?

**Comment by hhlvv** [comment]
vue.js의 프레임워크, javascript에서 bootstrap을 쓰듯이 쓰는 vuetify를 사용
하지만 cli 프로젝트에 추가를 하려는데 추가가 되지 않는 문제 발생.
1. vue ui 를 실행하여 GUI 화면에서 Plugins를 추가하라고 했으나 나오지 않는 화면만 뜸
![image](https://user-images.githubusercontent.com/19526984/74733340-77af4e80-528f-11ea-80b4-06a6b33f5b7a.png)

왜 프로젝트도 없다고 하는것인지..

2. 제대로 깔리지 않았던지? 위치의 문제 
App.vue 에서 v-app 으로 태그를 변경 시, 제대로 화면에서 나타나짐
![image](https://user-images.githubusercontent.com/19526984/74733413-a1687580-528f-11ea-9641-5f44dbbb4a5d.png)

하지만, views 내의 Home.vue에 수정을 하면 
![image](https://user-images.githubusercontent.com/19526984/74733490-c826ac00-528f-11ea-8392-dfc3ecdc64e6.png)

not defined발생.

**Comment by jongfeel** [comment]
vuetify 설정의 문제인 것 같은데, 한번 찾아보고 얘기해 드릴께요
